development:
  adapter: mysql2
  encoding: utf8
  database: ireadpaper_development
  host: localhost
  username: root
  password: root
test:
  adapter: mysql2
  encoding: utf8
  database: ireadpaper_test
  host: localhost
  username: root
  password: root
production:
  adapter: mysql2
  encoding: utf8
  database: ireadpaper_production
  host: localhost
  username: root
  password: root